# Generated by Django 4.0.4 on 2022-05-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='User ID')),
                ('name', models.TextField(verbose_name='User name')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
