# Generated by Django 4.0.4 on 2022-05-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btcPrice', models.TextField(verbose_name='BTC Price')),
                ('fiatPrice', models.TextField(verbose_name='Fiat Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Receiving time')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
