# Generated by Django 4.0.4 on 2022-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.TextField(choices=[(1, 'reject'), (2, 'done'), (3, 'send')], null=True, verbose_name='Status'),
        ),
    ]
