# Generated by Django 4.0.4 on 2022-05-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_alter_message_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfRequisites', models.TextField(verbose_name='Requisites Type')),
                ('number', models.TextField(verbose_name='Number')),
            ],
            options={
                'verbose_name': 'TypeofRequisites',
            },
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btcPrice', models.TextField(verbose_name='BTC Price')),
                ('fiatPrice', models.TextField(verbose_name='Fiat Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Receiving time')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.type', verbose_name='Requisites Type')),
            ],
            options={
                'verbose_name': 'Requisites',
            },
        ),
    ]
