# Generated by Django 4.0.4 on 2022-05-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_type_requisites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type of Requisites'},
        ),
    ]
