# Generated by Django 4.0.4 on 2022-05-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0009_alter_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ugc.type', verbose_name='Requisites Type'),
        ),
    ]
