# Generated by Django 4.0.4 on 2022-05-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0010_alter_requisites_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Profile'),
        ),
    ]
