# Generated by Django 4.0.4 on 2022-05-15 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0011_requisites_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Profile'),
        ),
    ]
